# Select beams with different moments signs at each end
Visualization of beams that needs to be checked/re-joined

In [1]:
import pandas as pd
import numpy as np
import os
import lib.csiapi as csiapi
import lib.util as util

%load_ext autoreload
%autoreload 2

ETABSObject, SapModel = csiapi.get_active_etabs_object()
# create folder for temporary csv files
csv_folder_path = os.getcwd() + r'\csv'
if not os.path.exists(csv_folder_path):
    os.makedirs(csv_folder_path)

Succesfully created helper object
Succesfully created SapModel

In [2]:
SapModel.Analyze.RunAnalysis()
print(SapModel.DatabaseTables.SetLoadCombinationsSelectedForDisplay(""))
print(SapModel.DatabaseTables.SetLoadCasesSelectedForDisplay("Dead"))

0

In [3]:
beam_table_dead = csiapi.get_table_display(SapModel, "Element Forces - Beams")

In [4]:
beam_table_dead

,Story,Beam,Unique Name,Output Case,Case Type,Step Type,Step Number,Step Label,Station,P,V2,V3,T,M2,M3,Element,Elem Station,Location
0,Story5,B277,298,Dead,LinStatic,NaN,NaN,NaN,0.3500,-27.8235,-9.8510,-0.0580,-0.0113,-0.1828,-8.0551,298,0.3500,NaN
1,Story5,B277,298,Dead,LinStatic,NaN,NaN,NaN,0.8318,-27.8235,-8.1480,-0.0580,-0.0113,-0.1549,-3.7190,298,0.8318,NaN
2,Story5,B277,298,Dead,LinStatic,NaN,NaN,NaN,1.3136,-27.8235,-6.4451,-0.0580,-0.0113,-0.1269,-0.2034,298,1.3136,NaN
3,Story5,B277,298,Dead,LinStatic,NaN,NaN,NaN,1.7955,-27.8235,-4.7421,-0.0580,-0.0113,-0.0990,2.4917,298,1.7955,NaN
4,Story5,B277,298,Dead,LinStatic,NaN,NaN,NaN,2.2773,-27.8235,-3.0391,-0.0580,-0.0113,-0.0710,4.3662,298,2.2773,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8302,Lantai Atap,B226,1089,Dead,LinStatic,NaN,NaN,NaN,7.0000,-7.7160,33.3471,0.0141,-0.7100,-0.0125,18.0648,1089-2,2.5000,NaN
8303,Lantai Atap,B226,1089,Dead,LinStatic,NaN,NaN,NaN,7.5000,-7.7160,44.5808,0.0141,-0.7100,-0.0195,-1.5215,1089-2,3.0000,NaN
8304,Lantai Atap,B226,1089,Dead,LinStatic,NaN,NaN,NaN,8.0000,-7.7160,53.3117,0.0141,-0.7100,-0.0266,-26.0989,1089-2,3.5000,NaN
8305,Lantai Atap,B226,1089,Dead,LinStatic,NaN,NaN,NaN,8.5000,-7.7160,59.5400,0.0141,-0.7100,-0.0336,-54.4161,1089-2,4.0000,NaN
8306,Lantai Atap,B226,1089,Dead,LinStatic,NaN,NaN,NaN,9.0000,-7.7160,63.2655,0.0141,-0.7100,-0.0407,-85.2217,1089-2,4.5000,NaN

In [5]:
unique_name = beam_table_dead['Unique Name'].drop_duplicates()

In [6]:
weird_beams = []
for i in unique_name:
    idx = beam_table_dead['Unique Name'] == i
    temp_table = beam_table_dead["M3"].loc[idx]
    if temp_table.iloc[-1] * temp_table.iloc[0] < 0:
        weird_beams.append(i)
        SapModel.FrameObj.SetSelected(str(i),True)